# Generated by Django 5.2.8 on 2025-11-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grupo_familiar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=254, verbose_name="Nome Completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("senha", models.CharField(max_length=254, verbose_name="Senha")),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_perfil/",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("adminFamilia", "Administrador da Família"),
                            ("usuario", "Usuário"),
                        ],
                        default="usuario",
                        max_length=50,
                        verbose_name="Papel do Usuário",
                    ),
                ),
                (
                    "id_familia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="grupo_familiar.familia",
                        verbose_name="Família",
                    ),
                ),
            ],
        ),
    ]
