# Banco de Dados (Supabase) 
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate 
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS (Configurado para pegar exclusivamente a URL da Vercel via variável)
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000